### ISSUE TITLE
What is password of user "builder" or su

### ISSUE THREAD

**Issue by murarisumit** [alljoynsville/general#1]
I need to install packages on this image, how it can be done ?

**Comment by alljoynsville** [comment]
no password. instead, run another docker:
`docker exec -it [image_instance_name] bash`
here you are root

**Comment by murarisumit** [comment]
@alljoynsville  Here too it logs-in with user builder, not able to execute "sudo apt-get update"

**Comment by alljoynsville** [comment]
docker exec can specify user:
docker exec -it -u root [image_instance_name] bash
